### PR TITLE
Bugfix: Cross product was not returning a 4d vector

### PR DESCRIPTION
**Pull request by ARoefer**
The cross product calculation in "symengine_wrappers.py" was not returning a 4d vector, but a simple 3d one. Since Giskard uses a 4d homogeneous coordinate system, this function should follow that scheme.

### CODE REVIEW

**Comment by ichumuh** [comment]
I'm not sure if I agree. There could be cases where you want to use the cross product on "normal" 3d vectors. Also, having the cross product return a 4d vector but actually calculating the 3d cross product and just adding a zero can be confusing.
I prefer if you'd just add the 0 if you need it.

**Comment by ARoefer** [comment]
I think it is in line with the way the other wrapper functions operate. All of them generate 4d objects for or from objects in a 4d world. I think that it is sensible for the cross product to return a vector (_, _, _, 0), because it makes the result immediately usable with the rest of the 4d objects.
I agree however, that just attaching the 0 is bad practice. My first idea would be to raise an exception for inputs with "w != 0" and to do the same for inputs which are not 4d. The first condition is impossible to check with symbols though.

**Comment by ichumuh** [comment]
Yes all of the generator functions return 4d stuff, but for functions like norm, dot and scale, it depends on the input. And our cross is only defined for 3d vectors. Also, do we always want the result to be a vector?
Maybe there are situations where we want a 1 in the last slot. So why not vector3(cross(a,b)) or point3(cross(a,b)) depending on what you currently need?

**Comment by ichumuh** [comment]
Now that I think about it, the implementations for norm, dot and scale are probably buggy, if you use arrays with 1 or 0 at the end...
I don't really want them to assume that the last entry is to be ignored, because then you can't use them for anything else.
I want them to work the same way as other implementations for example the numpy one.

**Comment by ARoefer** [comment]
The way I understand the homogeneous 4d transformation scheme, it differentiates between vectors and points by use of the "w" coordinate. w = 0 -> vector, w != 0 -> point. The implementations of dot, norm and scale are correct in my opinion, because all of these operations make no sense for points. Points as entities have neither a direction, nor a length, nor any scalable size. I think it is in line with mathematic conventions to not ignore this distinction and put the onus on the developer to only perform semantically sensible operations.
Note that there are already operations in this system, which you are allowed to perform, but make no semantic sense, thus yielding incorrect results. An example of such a case is vector - point -> w = -1.

**Comment by ichumuh** [comment]
Good point, that these operations don't make sense on points, thats good enough for me.
Regarding the cross product, i think we can just do something like this:
```
def cross(u, v):
    if len(u) != len(v):
        raise Exception('something meaningful')
    if len(u) == 3:
        return sp.Matrix([u[1] * v[2] - u[2] * v[1],
                          u[2] * v[0] - u[0] * v[2],
                          u[0] * v[1] - u[1] * v[0]])
    elif len(u) == 4:
        return sp.Matrix([u[1] * v[2] - u[2] * v[1],
                          u[2] * v[0] - u[0] * v[2],
                          u[0] * v[1] - u[1] * v[0],
                          0])
```
if's should be fine here because the lengths of the input vectors are known when we write the expressions.

**Comment by ARoefer** [comment]
I like that solution, it's a good compromise.

**Comment by ichumuh** [comment]
I have pushed my proposed changes for cross(). It seems like all of your other changes were also included in your other pull request, so I'm closing this one.

**Pull request closed without merging**
