### PR TITLE
Boxy Update

### PR DESCRIPTION
**Pull request by artnie**
Update the launch and config files for real boxy and boxy sim. 

The config is split only for different joint velocity caps, since simulation can be more reckless. Also simulation accepts more end effectors to move via interactive markers.

### CODE REVIEW

**Comment by ichumuh** [comment]
Could it be that there is a pr for iai_boxy_sim missing?

**Comment by artnie** [comment]
Maybe, well there is now, see https://github.com/code-iai/iai_boxy_sim/pull/5. Did you have an issue with the giskard sim launcher? `iai_boxy_sim` now excludes the navp_faker, since it doesn't update when Boxy is moved by giskard. The result was a very jumpy Boxy with two base_footprint publishers. Also I added the gripper joints to the `ros_control_sim.yaml` but leaving them out doesn't bther giskard very much.

**Comment by artnie** [comment]
Oh, and check if you have the latest boxy description from iai_robots. The UR descriptions were updated and Boxys URDF needed to as well.

**Comment by ichumuh** [comment]
thx

**Pull request merged**
